dataset:
  org_dir: /kaggle/input/fork-of-notebook85e3d82656/mitdb
  preprocessing_dir: /kaggle/input/fork-of-notebook85e3d82656/preprocessed
  output_dir:  /kaggle/input/fork-of-notebook85e3d82656/outputs
  num_leads: 2

preproc:
  raw_data_hdf5_exists: True
  clustering_model_exists: True
  use_pca: true
  clustering_sample_fraction: 0.1
  sentence_sample_fraction: 0.2
  mask_ratio: 0.15
  seq_len: 5000

train:
  num_epochs: 50
  batch_size: 16
  learning_rate: 0.0001
  pretrain_sample_fraction: 1.0
  device: cuda
  train_data_exists: True
