dataset:
  org_dir: /kaggle/working/ECGBERT-reproduce-project-/ptbdb
  preprocessing_dir: /kaggle/working/ECGBERT-reproduce-project-/preprocessed
  output_dir:  /kaggle/working/ECGBERT-reproduce-project-/outputs
  num_leads: 12

preproc:
  raw_data_hdf5_exists: False
  clustering_model_exists: False
  use_pca: true
  clustering_sample_fraction: 0.1
  sentence_sample_fraction: 0.2
  mask_ratio: 0.15

train:
  num_epochs: 500
  batch_size: 32
  learning_rate: 0.0005
  pretrain_sample_fraction: 1.0
  device: cuda
  train_data_exists: False
